/**
 * Build script: bundle all locale JSON files into a single JS file
 * that works on file:// protocol (no fetch needed).
 *
 * Usage: node build-locales.js
 */
const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'locales');
const outFile = path.join(__dirname, 'locales-bundle.js');

const files = fs.readdirSync(localesDir).filter(f => f.endsWith('.json'));
const bundle = {};

for (const file of files) {
    const lang = file.replace('.json', '');
    const data = JSON.parse(fs.readFileSync(path.join(localesDir, file), 'utf8'));
    bundle[lang] = data;
}

const js = `// Auto-generated by build-locales.js – do not edit manually.\nwindow.__LOCALES__ = ${JSON.stringify(bundle)};\n`;

fs.writeFileSync(outFile, js, 'utf8');

const size = (Buffer.byteLength(js) / 1024).toFixed(1);
console.log(`Built locales-bundle.js (${files.length} locales, ${size} KB)`);
